# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev
  - sudo apt-get install -y gnuplot

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make

