os: Visual Studio 2013
configuration: Release

install:
  - git clone -q --branch=master https://github.com/tronkko/dirent.git C:\projects\dirent

build_script:
  - mkdir build
  - cd build
  - cmake .. -G"Visual Studio 12 2013" -DCMAKE_INCLUDE_PATH="C:\projects\dirent\include"

matrix:
  fast_finish: true

