os: Visual Studio 2013
configuration: Release

install:
  - git clone -q --branch=master https://github.com/tronkko/dirent.git C:\projects\dirent
  - cmd: choco install gnuplot
  - cmd: choco install opencv -version 2.4.13

environment:
  DIRENT_INCLUDE_DIR: C:\projects\dirent\include

build_script:
  - mkdir build
  - cd build
  - cmake .. -G"Visual Studio 12 2013"

matrix:
  fast_finish: true

